version: '3'
services:
    pet_gateway:
        image: nginx:alpine
        volumes:
            - "./nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/ssl:/etc/ssl"
            # - "../:/var/www/html"
        ports:
            - "${APP_CLIENT_PORT}:${APP_CLIENT_PORT}"
            # - "443:443"
        environment:
            - NGINX_HOST=localhost
        restart: always
        depends_on:
            - pet_frontend
            - pet_backend
        networks:
            - app-network
    pet_frontend:
        build: ./client
        container_name: pet_frontend
        restart: always
        volumes:
            - "./client:/app"
        depends_on:
            - pet_backend
        networks:
            - app-network

    pet_backend:
        build: ./server
        container_name: pet_backend
        restart: always
        env_file:
            - ".env"
        depends_on:
            - pet_db
        volumes:
            - './server:/usr/src/app'
        networks:
            - app-network
    pet_db:
        build: ./db
        container_name: pet_db
        restart: always
        env_file:
            - ".env"
        # volumes:
        #     - "./db/data:/var/lib/postgres"
        #     - "./db/log:/var/log/postgres"
        #     - "./config/conf.d:/etc/postgres/conf.d"
        networks:
            - app-network


    # memcached:
    #     container_name: memcached
    #     image: memcached:latest
    #     restart: always
    #     environment:
    #         # Memcached memory limit in megabytes
    #         - MEMCACHED_MEMORY_LIMIT=1024
    #     expose:
    #         - '11211'
        # networks:
        #     - app-network

networks:
    app-network:
        driver: bridge